### ISSUE TITLE
Define initial roadmap

### ISSUE THREAD

**Issue by sergefdrv** [replica-io/replica-io#1]
The initial roadmap should outline important milestones towards reaching the goal of the project.

**Comment by sergefdrv** [comment]
I updated the description of the issue. Now it will not target an MVP, but stretch up to the goal of the project. The milestones will be then refined and sub-milestones added as needed down the road.

**Comment by sergefdrv** [comment]
Here's a draft of the roadmap:

- **Milestone 1: Prototype**
  This milestone delivers a prototype that clearly demonstrates how the framework will look like once fully implemented. The prototype includes all essential features and properly implements a small selected part of the framework, though does not yet constitute an MVP. It still remains for the most part rough, but the selected part is fully implemented, documented, and polished up. This would be good time to start actively attracting broader attention to the project.
  Achieving this includes the following steps.
   - _Generating core ideas._ This step requires great creativity and domain expertise. It consists of exploring the relevant state of the art and coming up with clever ideas for fulfilling project's key technical objectives.
   - _Formulating core concepts._ This step requires clear abstract thinking, as well as decent domain expertise. It consists of developing rough ides into clear concepts for the main principles of composing distributed replication mechanisms that provide a solid foundation for the whole framework.
   - _Developing PoC implementation._ This step requires good critical thinking and technical skills. It consists of verifying the feasibility of the core concepts by implementing them in real code.
   - _Developing prototype implementation._ This step requires talent and experience in software engineering. It consists of fully implementing, documenting and polishing up a selected part of the PoC implementation.
- **Milestone 2: MVP**
  This milestone delivers an MVP version of the framework that unlocks some actual, though not yet industrial, use cases, e.g. implementing distributed protocols for research purposes. The features included in the MVP are fully implemented, documented, and polished up. At this point the project should be well supported and sustainable.
- **Milestone 3: Ready for Integration**
 This milestone delivers a first release of the framework ready for integration into a real production system.

**Comment by sergefdrv** [comment]
> Achieving this includes the following steps

Perhaps, those steps should be turned into sub-milestones, e.g. "M0.1: Core Ideas Generated", "M0.2: Core Concepts Formulated", ... , "M1: Prototype".

**Comment by sergefdrv** [comment]
The roadmap outline with links to GitHub milestones:

- [ ] [M0.1: Initial Ideas](https://github.com/replica-io/replica-io/milestone/1) — exploring the relevant state of the art and coming up with clever ideas
- [ ] [M0.2: Core Concepts](https://github.com/replica-io/replica-io/milestone/2) — developing the rough ideas into clearly formulated concepts
- [ ] [M0.3: PoC Implementation](https://github.com/replica-io/replica-io/milestone/3) — verifying the feasibility of the core concepts by implementing them in real code
- [ ] [M1: Prototype](https://github.com/replica-io/replica-io/milestone/4) — clearly demonstrating how the framework will look like once fully implemented
- [ ] [M2: MVP](https://github.com/replica-io/replica-io/milestone/5) — unlocking some actual, though not yet industrial, use cases
- [ ] [M3: Ready for Integration](https://github.com/replica-io/replica-io/milestone/6) — releasing the framework ready for integration into a real production system
